### ISSUE TITLE
Cabal install warnings

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/gf-canonical-transforms#4]
Cabal install generates warnings:

```
Warning: The install command is a part of the legacy v1 style of cabal usage.
(...)
Warning: gf-canonical-transforms.cabal:0:0: version with tags
(...)
Warning: could not create a symlink in /Users/peter/.cabal/bin for
gf-conflate-params because the file exists there already but is not managed by
cabal. You can create a symlink for this executable manually if you wish. The
executable file has been installed at
/Users/peter/.cabal/bin/gf-conflate-params
```

I don't understand the warning about "version with tags", perhaps nothing to care about.

The last warning: apparently you copy the executable to the binary, and then cabal cannot create a symlink. There should be a way to suppress that warning.

**Comment by Thomas-H** [comment]
The version in the cabal file is 0.1-git, I don't know the new version why Cabal complains about that. Nevertheless, I changed it.

I think the symlink issue is a problem with how you have configured cabal on your system.

**Comment by heatherleaf** [comment]
> I think the symlink issue is a problem with how you have configured cabal on your system.

It seems it's a Cabal bug which won't be fixed: https://github.com/haskell/cabal/issues/1452

**Comment by Thomas-H** [comment]
So, nothing we can do about that...

**Comment by AaronNGray** [comment]
Working from scratch how to I prevent this happening on Ubuntu on Windows WSL or on .Mac OSX ?

**Comment by daherb** [comment]
The code is outdated and not supported anymore. But if you really insist on trying to compile it you can start from the attached stack file
[stack.yaml.gz](https://github.com/MUSTE-Project/gf-canonical-transforms/files/7804336/stack.yaml.gz)

**Comment by AaronNGray** [comment]
Okay I realize I was using a very old version of cabal on Ubuntu, for some reason they have very old version of ghc, cabal and the haskell-platform.
